CREATE TABLE Temp_table (
    "App Name" TEXT,
    "App Id" TEXT PRIMARY KEY,
    "Category" TEXT,
    "Rating" FLOAT,
    "Rating Count" INT,
    "Installs" BIGINT,
    "Minimum Installs" BIGINT,
    "Maximum Installs" BIGINT,
    "Free" BOOLEAN,
    "Price" FLOAT,
    "Currency" TEXT,
    "Size" TEXT,
    "Minimum Android" TEXT,
    "Developer Id" TEXT,
    "Developer Website" TEXT,
    "Developer Email" TEXT,
    "Released" DATE,
    "Last Updated" DATE,
    "Content Rating" TEXT,
    "Privacy Policy" TEXT,
    "Ad Supported" BOOLEAN,
    "In App Purchases" BOOLEAN,
    "Editors Choice" BOOLEAN,
    "Scraped Time" TIMESTAMP
);
